# Generated by Django 4.1.1 on 2022-10-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='bank',
            new_name='bank_id',
        ),
    ]
